In [1]:
numbers = [46,79,77,45,57,34,44,13,32,88,86,82,91,97,89,1,48,31,18,10,55,74,24,11,80,78,28,37,47,17,21,61,26,85,99,96,23,70,3,54,5,41,50,63,14,64,42,36,95,52,76,68,29,9,98,35,84,83,71,49,73,58,56,66,92,30,51,20,81,69,65,15,6,16,39,43,67,7,59,40,60,4,90,72,22,0,93,94,38,53,87,27,12,2,25,19,8,62,33,75]

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("day4data.txt")

In [4]:
df

             boards
0    84 94 24 52 44
1    96 33 74 35 13
2    60 51 41 19 95
3    50 93 27 40  1
4    67 23 37 88 85
..              ...
495  38 46 18 54 76
496  25 22 47 10 11
497  63 29 74 71 92
498  75 98  0 65  4
499  87 14 13 64 12

[500 rows x 1 columns]

In [9]:
split = pd.DataFrame(columns = range(5), index = range(500))

In [16]:
for i in range(len(df)):
    a = df.loc[i]["boards"]
    splitted = a.split()
    split.iloc[i] = splitted

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [17]:
split = split.astype(int)

In [58]:
split2 = split

In [59]:
i = 0

In [36]:
import numpy as np

In [85]:
grids = []
for i in range(0, 500, 5):
    grids.append(split[i:i+5])
print(grids[0])

    0   1   2   3   4
0  84  94  24  52  44
1  96  33  74  35  13
2  60  51  41  19  95
3  50  93  27  40   1
4  67  23  37  88  85

In [86]:
for j in range(len(numbers)):
    for i in range(100):
        grids[i] = grids[i].replace([numbers[j]], np.nan)
        rowsNA = grids[i].isnull().sum(axis=1).tolist()
        if 5 in rowsNA:
            print("row", i, j)
            break
        columnsNA = grids[i].isnull().sum(axis=0).tolist()
        if 5 in columnsNA:
            print("column", i, j)
            break

row 60 26
column 51 27
column 51 28
column 51 29
column 45 30
column 45 31
column 45 32
column 45 33
row 31 34
row 31 35
row 31 36
column 2 37
column 2 38
column 2 39
column 2 40
column 2 41
column 2 42
column 2 43
column 2 44
column 2 45
column 2 46
column 2 47
column 0 48
column 0 49
column 0 50
column 0 51
column 0 52
column 0 53
column 0 54
column 0 55
column 0 56
column 0 57
column 0 58
column 0 59
column 0 60
column 0 61
column 0 62
column 0 63
column 0 64
column 0 65
column 0 66
column 0 67
column 0 68
column 0 69
column 0 70
column 0 71
column 0 72
column 0 73
column 0 74
column 0 75
row 0 76
row 0 77
row 0 78
row 0 79
row 0 80
row 0 81
row 0 82
row 0 83
row 0 84
row 0 85
row 0 86
row 0 87
row 0 88
row 0 89
row 0 90
row 0 91
row 0 92
row 0 93
row 0 94
row 0 95
row 0 96
row 0 97
row 0 98
row 0 99

In [91]:
sum(grids[60].sum()) * numbers[26]

22680.0

In [145]:
grids = []
for i in range(0, 500, 5):
    grids.append(split[i:i+5])

In [146]:
fullgrids = 0
for j in range(len(numbers)):
    for i in range(100):        
        grids[i] = grids[i].replace([numbers[j]], np.nan)
        rowsNA = grids[i].isnull().sum(axis=1).tolist()
        columnsNA = grids[i].isnull().sum(axis=0).tolist()
        
        if 5 in rowsNA:
            print(grids[i])
            lastwinner = grids[i].copy()
            lastnumber = j
            print("row", i, j)
            #grids[i].fillna(-1, inplace = True)
            grids[i].values[:] = -100
            fullgrids += 1

        elif 5 in columnsNA:
            print(grids[i])
            lastwinner = grids[i].copy()
            lastnumber = j
            print("column", i, j)
            #grids[i].fillna(-1, inplace = True)
            grids[i].values[:] = -100
            fullgrids += 1

        0     1     2     3     4
300  19.0  85.0  36.0  73.0  71.0
301  65.0  62.0  14.0  52.0   3.0
302  30.0  83.0   NaN  41.0   5.0
303   NaN  15.0   0.0  61.0  95.0
304   NaN   NaN   NaN   NaN   NaN
row 60 26
        0     1   2     3     4
255   8.0   NaN NaN  38.0  59.0
256   NaN  94.0 NaN   NaN   NaN
257  81.0   NaN NaN   NaN   NaN
258  43.0  25.0 NaN  49.0  67.0
259  22.0  95.0 NaN   NaN   NaN
column 51 27
        0     1     2     3     4
340   NaN  56.0  41.0   8.0   NaN
341  53.0  38.0  69.0  62.0  67.0
342   NaN   6.0  35.0   NaN  66.0
343   NaN  84.0  83.0  49.0   2.0
344   NaN   NaN   NaN   NaN   NaN
row 68 28
        0     1   2     3     4
225  60.0   6.0 NaN  29.0  12.0
226   NaN  68.0 NaN  71.0   NaN
227   3.0   NaN NaN  63.0  95.0
228   NaN  52.0 NaN   NaN   NaN
229  14.0  64.0 NaN  94.0  20.0
column 45 30
      0   1     2     3     4
355  19 NaN   NaN  14.0   NaN
356   4 NaN  92.0  43.0   5.0
357  96 NaN  67.0   NaN  69.0
358  50 NaN  49.0   NaN   NaN
359  27 NaN   NaN  98.0  59.0
column 71 31
      0   1     2     3     4
355  19 NaN   NaN  14.0   NaN
356   4 NaN  92.0  43.0   5.0
357  96 NaN  67.0   NaN  69.0
358  50 NaN  49.0   NaN   NaN
359  27 NaN   NaN  98.0  59.0
column 71 32
      0   1     2     3     4
355  19 NaN   NaN  14.0   NaN
356   4 NaN  92.0  43.0   5.0
357  96 NaN  67.0   NaN  69.0
358  50 NaN  49.0   NaN   NaN
359  27 NaN   NaN  98.0  59.0
column 71 33
        0     1     2     3     4
370  14.0  75.0  39.0   NaN  42.0
371   NaN   NaN  99.0   NaN   NaN
372   NaN   NaN   NaN   NaN   NaN
373  68.0  38.0  25.0   NaN  49.0
374   NaN  20.0   NaN  36.0  67.0
row 74 33
        0     1     2     3     4
155   NaN   NaN  52.0  75.0   NaN
156   8.0  33.0   NaN   9.0   NaN
157   NaN   NaN   NaN   NaN   NaN
158  64.0  14.0  49.0  68.0  72.0
159   NaN  66.0  35.0  36.0   NaN
row 31 34
      0   1     2     3     4
355  19 NaN   NaN  14.0   NaN
356   4 NaN  92.0  43.0   5.0
357  96 NaN  67.0   NaN  69.0
358  50 NaN  49.0   NaN   NaN
359  27 NaN   NaN  98.0  59.0
column 71 34
        0     1     2     3     4
395  14.0   NaN   NaN   NaN  51.0
396   NaN   NaN   NaN   NaN   NaN
397   0.0  29.0  15.0  25.0  64.0
398   NaN  16.0  35.0  60.0  95.0
399  41.0  54.0  72.0   NaN  87.0
row 79 34
        0   1     2     3     4
355  19.0 NaN   NaN  14.0   NaN
356   4.0 NaN  92.0  43.0   5.0
357   NaN NaN  67.0   NaN  69.0
358  50.0 NaN  49.0   NaN   NaN
359  27.0 NaN   NaN  98.0  59.0
column 71 35
       0     1   2     3     4
10  54.0  38.0 NaN  29.0  51.0
11  16.0  19.0 NaN   NaN  63.0
12  76.0   NaN NaN  30.0   NaN
13   NaN  81.0 NaN   NaN  90.0
14  60.0  94.0 NaN   NaN  83.0
column 2 37
        0     1   2   3     4
470  36.0  43.0   4 NaN  90.0
471  69.0   NaN  95 NaN  65.0
472   6.0  56.0  30 NaN  22.0
473   NaN  50.0  63 NaN  76.0
474  54.0  92.0  51 NaN   NaN
column 94 38
        0     1   2   3     4
470  36.0  43.0   4 NaN  90.0
471  69.0   NaN  95 NaN  65.0
472   6.0  56.0  30 NaN  22.0
473   NaN  50.0  63 NaN  76.0
474   NaN  92.0  51 NaN   NaN
column 94 39
        0     1     2     3     4
185  22.0  36.0  33.0   NaN   NaN
186  64.0   NaN  25.0  38.0   NaN
187   NaN   NaN   NaN   NaN   NaN
188  35.0   NaN   NaN  50.0   7.0
189  15.0   NaN  58.0  27.0  66.0
row 37 40
        0     1   2   3     4
470  36.0  43.0   4 NaN  90.0
471  69.0   NaN  95 NaN  65.0
472   6.0  56.0  30 NaN  22.0
473   NaN  50.0  63 NaN  76.0
474   NaN  92.0  51 NaN   NaN
column 94 40
        0     1     2     3     4
150   NaN   NaN   NaN   NaN   NaN
151   NaN  22.0   NaN  15.0  63.0
152  36.0   NaN   NaN   NaN  49.0
153   NaN  27.0  83.0  40.0   NaN
154   8.0   7.0   NaN  69.0  33.0
row 30 41
        0     1   2   3     4
470  36.0  43.0   4 NaN  90.0
471  69.0   NaN  95 NaN  65.0
472   6.0  56.0  30 NaN  22.0
473   NaN  50.0  63 NaN  76.0
474   NaN  92.0  51 NaN   NaN
column 94 41
        0     1   2   3     4
470  36.0  43.0   4 NaN  90.0
471  69.0   NaN  95 NaN  65.0
472   6.0  56.0  30 NaN  22.0
473   NaN   NaN  63 NaN  76.0
474   NaN  92.0  51 NaN   NaN
column 94 42
        0   1     2   3     4
350   NaN NaN   9.0   8   NaN
351   NaN NaN   NaN  60   NaN
352  59.0 NaN  87.0  43   NaN
353   NaN NaN  51.0  98  25.0
354  53.0 NaN   4.0  42  52.0
column 70 43
        0     1     2     3   4
435  64.0  68.0  14.0   2.0 NaN
436   NaN  22.0   NaN   NaN NaN
437   NaN   NaN   NaN   NaN NaN
438  81.0   NaN   NaN  27.0 NaN
439   NaN  36.0   0.0  58.0 NaN
row 87 43
        0   1     2     3     4
455   NaN NaN  59.0  72.0   NaN
456  14.0 NaN   NaN  87.0   NaN
457   NaN NaN   NaN  81.0   NaN
458  68.0 NaN   9.0  35.0   NaN
459  49.0 NaN   NaN   NaN  20.0
column 91 43
        0     1     2   3     4
470  36.0  43.0   4.0 NaN  90.0
471  69.0   NaN  95.0 NaN  65.0
472   6.0  56.0  30.0 NaN  22.0
473   NaN   NaN   NaN NaN  76.0
474   NaN  92.0  51.0 NaN   NaN
column 94 43
       0     1     2     3     4
80   NaN   NaN  87.0  12.0  75.0
81  95.0  20.0  93.0  72.0   NaN
82  90.0   NaN   NaN   NaN  66.0
83   NaN   NaN   NaN   NaN   NaN
84   NaN   NaN  60.0   NaN  62.0
row 16 44
       0     1     2     3     4
85  20.0  25.0   0.0   NaN  83.0
86   NaN   NaN   NaN   NaN   NaN
87   NaN  58.0  65.0  76.0   NaN
88   NaN  15.0   NaN  81.0   NaN
89  49.0  90.0  16.0  42.0   NaN
row 17 44
        0   1     2   3     4
350   NaN NaN   9.0   8   NaN
351   NaN NaN   NaN  60   NaN
352  59.0 NaN  87.0  43   NaN
353   NaN NaN  51.0  98  25.0
354  53.0 NaN   4.0  42  52.0
column 70 44
       0     1     2     3   4
90  87.0   NaN  68.0   NaN NaN
91  69.0  40.0   NaN  71.0 NaN
92  12.0   NaN   NaN  95.0 NaN
93  42.0   2.0   NaN  72.0 NaN
94   NaN   7.0   NaN  94.0 NaN
column 18 45
        0   1     2   3     4
350   NaN NaN   9.0   8   NaN
351   NaN NaN   NaN  60   NaN
352  59.0 NaN  87.0  43   NaN
353   NaN NaN  51.0  98  25.0
354  53.0 NaN   4.0  42  52.0
column 70 45
       0     1   2     3     4
15   NaN  56.0 NaN  68.0   NaN
16   6.0   NaN NaN  22.0  27.0
17  75.0   NaN NaN   NaN   NaN
18  29.0   NaN NaN  73.0   NaN
19   7.0  16.0 NaN  12.0   NaN
column 3 46
        0   1     2     3     4
240  98.0 NaN  62.0  58.0   NaN
241  67.0 NaN  81.0  93.0  19.0
242   NaN NaN   NaN   NaN  51.0
243   8.0 NaN   NaN   NaN  92.0
244  25.0 NaN  76.0   NaN   4.0
column 48 46
        0   1     2     3     4
290  93.0 NaN  68.0   NaN  53.0
291   NaN NaN   NaN  22.0   NaN
292  56.0 NaN  30.0   9.0  35.0
293   NaN NaN  29.0  40.0   NaN
294   NaN NaN   NaN   NaN  15.0
column 58 46
        0   1     2     3     4
350   NaN NaN   9.0   8.0   NaN
351   NaN NaN   NaN  60.0   NaN
352  59.0 NaN  87.0  43.0   NaN
353   NaN NaN  51.0  98.0  25.0
354  53.0 NaN   4.0   NaN  52.0
column 70 46
      0     1     2     3   4
0  84.0  94.0   NaN  52.0 NaN
1   NaN  33.0   NaN  35.0 NaN
2  60.0  51.0   NaN  19.0 NaN
3   NaN  93.0  27.0  40.0 NaN
4  67.0   NaN   NaN   NaN NaN
column 0 48
       0     1   2     3     4
60   NaN   NaN NaN  72.0   NaN
61   NaN  81.0 NaN  52.0   NaN
62  56.0   NaN NaN   NaN  73.0
63  38.0   0.0 NaN  43.0   NaN
64   NaN  69.0 NaN   NaN  94.0
column 12 48
       0     1     2     3     4
65   7.0  59.0  76.0   NaN  43.0
66   NaN   NaN   NaN   4.0  83.0
67  22.0  62.0   NaN  16.0   NaN
68   NaN  27.0   NaN   NaN  87.0
69   NaN   NaN   NaN   NaN   NaN
row 13 48
        0     1     2     3   4
235  49.0  35.0   NaN   NaN NaN
236   NaN  51.0   NaN  94.0 NaN
237  65.0  83.0   NaN  27.0 NaN
238   NaN   NaN  29.0   NaN NaN
239  56.0   NaN  38.0  16.0 NaN
column 47 48
        0     1     2   3     4
275   NaN  59.0  90.0 NaN  15.0
276  33.0  16.0   NaN NaN   NaN
277   8.0  49.0  73.0 NaN  76.0
278  93.0   NaN  94.0 NaN   NaN
279  20.0   NaN  30.0 NaN  52.0
column 55 48
      0    1    2     3     4
105 NaN  NaN  NaN  73.0   NaN
106 NaN  NaN  0.0   NaN  93.0
107 NaN  7.0  NaN   NaN   NaN
108 NaN  NaN  NaN  81.0   NaN
109 NaN  8.0  NaN  29.0   NaN
column 21 49
      0     1     2     3     4
320 NaN  43.0   NaN  33.0   NaN
321 NaN  83.0  59.0   NaN  87.0
322 NaN   NaN   NaN  90.0  58.0
323 NaN   NaN  69.0  27.0   NaN
324 NaN   NaN   NaN   NaN   7.0
column 64 51
        0     1     2     3   4
460   NaN  66.0   NaN  29.0 NaN
461   NaN   NaN  81.0   NaN NaN
462   NaN  15.0  22.0  58.0 NaN
463  49.0   NaN  90.0  72.0 NaN
464   NaN  71.0   NaN   NaN NaN
column 92 51
        0     1     2     3     4
475  56.0   4.0   NaN   NaN  98.0
476  84.0  49.0   NaN  33.0   NaN
477   NaN  87.0  75.0  15.0   NaN
478   NaN   NaN   NaN   NaN   NaN
479  59.0  58.0   NaN  90.0  93.0
row 95 51
       0     1     2     3     4
50  75.0  90.0   NaN  59.0   NaN
51  84.0  38.0   NaN   NaN  73.0
52   NaN   NaN   NaN   NaN   NaN
53   NaN   NaN   4.0   NaN   NaN
54  15.0   NaN  67.0  12.0   NaN
row 10 52
        0     1     2    3     4
100  66.0   NaN   9.0  NaN   8.0
101   NaN   NaN   NaN  NaN   NaN
102   NaN   7.0  39.0  NaN   NaN
103   NaN   0.0   NaN  NaN   NaN
104   NaN  83.0  62.0  6.0  93.0
row 20 52

      0     1    2   3     4
5  12.0   NaN  6.0 NaN   NaN
6   NaN   NaN  NaN NaN  51.0
7  71.0  72.0  NaN NaN  73.0
8   NaN   NaN  NaN NaN  19.0
9  30.0  67.0  NaN NaN  62.0
column 1 54
     0   1     2     3     4
45  90 NaN   NaN   8.0   NaN
46  40 NaN   NaN  62.0   NaN
47  60 NaN   NaN   NaN   NaN
48  15 NaN   NaN   NaN   NaN
49  93 NaN  72.0   NaN  73.0
column 9 54
        0    1   2     3     4
400  58.0  2.0 NaN  51.0   NaN
401   NaN  NaN NaN  71.0   NaN
402  66.0  NaN NaN  38.0  62.0
403  87.0  NaN NaN  75.0   NaN
404   NaN  6.0 NaN   NaN  72.0
column 80 54
     0   1     2     3     4
45  90 NaN   NaN   8.0   NaN
46  40 NaN   NaN  62.0   NaN
47  60 NaN   NaN   NaN   NaN
48  15 NaN   NaN   NaN   NaN
49  93 NaN  72.0   NaN  73.0
column 9 55
        0     1     2     3     4
305   NaN  92.0  33.0   NaN   7.0
306   NaN   NaN   NaN   NaN   NaN
307   NaN   NaN   NaN   2.0   NaN
308   NaN   NaN   NaN  69.0   NaN
309  56.0  20.0  67.0   NaN  43.0
row 61 55
        0     1    2   3     4
310  38.0   NaN  NaN NaN   NaN
311   4.0   NaN  NaN NaN   NaN
312   NaN  94.0  2.0 NaN  72.0
313  27.0  58.0  NaN NaN  39.0
314   6.0  92.0  NaN NaN   NaN
column 62 55
        0     1     2     3   4
490   NaN  12.0  16.0   NaN NaN
491  59.0  27.0  58.0   NaN NaN
492  92.0   NaN  75.0  19.0 NaN
493   NaN   NaN   NaN  30.0 NaN
494   NaN  72.0   NaN  39.0 NaN
column 98 55
     0   1     2     3     4
45  90 NaN   NaN   8.0   NaN
46  40 NaN   NaN  62.0   NaN
47  60 NaN   NaN   NaN   NaN
48  15 NaN   NaN   NaN   NaN
49  93 NaN  72.0   NaN  73.0
column 9 56
        0     1     2     3     4
265   NaN   NaN  62.0   NaN  56.0
266   NaN  66.0  19.0   NaN  51.0
267  65.0   NaN  90.0  94.0   NaN
268   NaN   NaN  87.0  83.0  73.0
269   NaN   NaN   NaN   NaN   NaN
row 53 56
       0     1     2     3    4
270  2.0  92.0   NaN   4.0  NaN
271  NaN   NaN  81.0  20.0  NaN
272  NaN  39.0   NaN  15.0  7.0
273  NaN   NaN   NaN   NaN  NaN
274  NaN   NaN   NaN  12.0  NaN
row 54 56
        0     1   2     3     4
410   NaN  58.0 NaN   NaN   NaN
411  38.0   NaN NaN  56.0  90.0
412   NaN   NaN NaN   NaN  12.0
413   7.0   NaN NaN   NaN   NaN
414  93.0   NaN NaN  81.0  25.0
column 82 56
        0     1     2     3     4
430  51.0  43.0   NaN   NaN   NaN
431  16.0  56.0   NaN   NaN   NaN
432   NaN  72.0   NaN  39.0  65.0
433  66.0   NaN  93.0   NaN   NaN
434   NaN   NaN   NaN   NaN   NaN
row 86 56
     0   1     2     3     4
45  90 NaN   NaN   8.0   NaN
46  40 NaN   NaN  62.0   NaN
47  60 NaN   NaN   NaN   NaN
48  15 NaN   NaN   NaN   NaN
49  93 NaN  72.0   NaN  73.0
column 9 57
     0     1     2     3     4
55 NaN  93.0   NaN   NaN  56.0
56 NaN  19.0  20.0   8.0   NaN
57 NaN  73.0  22.0  60.0   NaN
58 NaN  27.0   NaN  38.0   NaN
59 NaN   NaN   NaN  87.0   NaN
column 11 57
       0     1     2     3     4
130  NaN  51.0   4.0   NaN  90.0
131  NaN  67.0   NaN  40.0   NaN
132  NaN   NaN   NaN   NaN   NaN
133  8.0  56.0  87.0   2.0   6.0
134  7.0  30.0   NaN   NaN  43.0
row 26 57
       0     1   2     3     4
25  75.0   NaN NaN   0.0   NaN
26   NaN  58.0 NaN  81.0  20.0
27   NaN   8.0 NaN  66.0   NaN
28  59.0  15.0 NaN   NaN  56.0
29   NaN   NaN NaN   NaN  73.0
column 5 58
     0   1     2     3     4
45  90 NaN   NaN   8.0   NaN
46  40 NaN   NaN  62.0   NaN
47  60 NaN   NaN   NaN   NaN
48  15 NaN   NaN   NaN   NaN
49  93 NaN  72.0   NaN  73.0
column 9 58
        0     1     2     3     4
200   NaN   NaN  19.0  49.0   NaN
201   7.0  58.0  72.0   NaN  12.0
202   NaN   NaN   NaN   NaN   NaN
203   NaN   NaN   NaN   NaN  65.0
204  69.0   NaN  75.0   NaN  73.0
row 40 58
      0     1     2     3     4
315 NaN   NaN  60.0   NaN   NaN
316 NaN   NaN   NaN   NaN  27.0
317 NaN  67.0   NaN   NaN   NaN
318 NaN   NaN   NaN  19.0   NaN
319 NaN   NaN  20.0   NaN   NaN
column 63 58
        0     1     2     3     4
450  94.0  92.0   NaN   NaN  60.0
451   NaN   NaN  39.0   NaN  73.0
452   NaN  12.0   NaN  49.0  40.0
453   NaN   NaN   NaN   NaN   NaN
454   NaN  75.0   NaN  65.0   NaN
row 90 58
     0   1     2     3     4
45  90 NaN   NaN   8.0   NaN
46  40 NaN   NaN  62.0   NaN
47  60 NaN   NaN   NaN   NaN
48  15 NaN   NaN   NaN   NaN
49  93 NaN  72.0   NaN  73.0
column 9 59
        0     1     2     3   4
230   NaN   NaN  40.0   NaN NaN
231  69.0  81.0   NaN   NaN NaN
232   NaN   NaN   NaN   7.0 NaN
233   NaN  20.0  27.0  93.0 NaN
234   NaN   NaN  43.0  39.0 NaN
column 46 59
        0     1     2   3     4
335   NaN  67.0  16.0 NaN  87.0
336   NaN  22.0   NaN NaN  65.0
337  73.0  15.0   NaN NaN   NaN
338  19.0   NaN   NaN NaN  56.0
339  60.0   NaN   NaN NaN  38.0
column 67 59
        0     1     2     3     4
380  38.0   NaN  25.0   NaN   NaN
381   NaN   NaN   NaN   NaN  67.0
382   8.0  53.0  92.0   NaN   NaN
383   NaN   NaN   NaN   NaN   NaN
384  66.0   NaN   NaN  75.0  16.0
row 76 59
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 60
       0     1     2   3     4
165  NaN  87.0   NaN NaN  75.0
166  0.0   2.0   NaN NaN   NaN
167  NaN   NaN  12.0 NaN  27.0
168  NaN  90.0   NaN NaN   NaN
169  NaN   NaN  72.0 NaN   4.0
column 33 60
      0     1    2     3     4
205 NaN   NaN  NaN   NaN  56.0
206 NaN   NaN  NaN  40.0  66.0
207 NaN   NaN  7.0   NaN   NaN
208 NaN   NaN  NaN   NaN  75.0
209 NaN  15.0  NaN   NaN   2.0
column 41 60
        0     1     2     3     4
385   NaN   NaN   NaN   NaN   NaN
386  51.0   NaN   NaN   NaN   NaN
387   NaN  27.0   NaN   2.0  67.0
388  19.0  69.0  16.0  40.0   NaN
389   NaN   NaN  38.0   NaN   8.0
row 77 60
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 61
        0     1     2   3     4
190  87.0  62.0  22.0 NaN   NaN
191   NaN   0.0   NaN NaN   NaN
192   NaN   NaN   NaN NaN  60.0
193   NaN   NaN   7.0 NaN   NaN
194  90.0  94.0  16.0 NaN  66.0
column 38 61
        0     1   2     3   4
215   NaN  40.0  56   NaN NaN
216  27.0  19.0  69  30.0 NaN
217   NaN   NaN   4   NaN NaN
218   NaN   NaN  94   NaN NaN
219  72.0  65.0  92   NaN NaN
column 43 61
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 62
        0     1     2     3   4
215   NaN  40.0   NaN   NaN NaN
216  27.0  19.0  69.0  30.0 NaN
217   NaN   NaN   4.0   NaN NaN
218   NaN   NaN  94.0   NaN NaN
219  72.0  65.0  92.0   NaN NaN
column 43 62
        0     1     2    3     4
295  43.0   NaN  69.0  NaN  65.0
296   NaN  16.0  15.0  NaN   6.0
297   NaN   NaN   NaN  NaN   NaN
298   NaN   NaN   NaN  7.0  22.0
299   8.0   NaN   NaN  NaN   NaN
row 59 62
        0     1     2     3    4
365  16.0   NaN   NaN  62.0  NaN
366   NaN   NaN  92.0  59.0  4.0
367   NaN   NaN   NaN   NaN  NaN
368   NaN  43.0   NaN  40.0  NaN
369  38.0   NaN  67.0  20.0  NaN
row 73 62
       0     1     2     3     4
20  20.0  62.0   NaN   NaN  12.0
21   NaN   NaN  40.0   8.0   NaN
22   NaN   NaN   NaN   NaN   NaN
23  72.0   NaN  19.0  65.0  22.0
24  30.0   NaN  27.0   NaN   NaN
row 4 63
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 63
        0   1     2     3     4
140   NaN NaN   7.0   NaN   NaN
141   NaN NaN  40.0  60.0   NaN
142  67.0 NaN   NaN   NaN   NaN
143   NaN NaN   NaN  90.0  75.0
144  81.0 NaN   NaN  94.0   NaN
column 28 63
      0     1   2     3     4
40  4.0  53.0 NaN   NaN   NaN
41  0.0   6.0 NaN   NaN   NaN
42  NaN  67.0 NaN   2.0   NaN
43  NaN   NaN NaN   NaN  30.0
44  NaN   NaN NaN  65.0   NaN
column 8 64
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 64
       0     1     2   3     4
70   NaN   6.0  53.0 NaN   NaN
71   NaN   NaN  81.0 NaN  25.0
72   NaN   NaN  20.0 NaN   7.0
73  72.0  19.0   NaN NaN   NaN
74   NaN  33.0   NaN NaN   NaN
column 14 64
        0     1     2     3     4
170  30.0   NaN   NaN  81.0  93.0
171   NaN   NaN   NaN  75.0  43.0
172   NaN   NaN   NaN   NaN   NaN
173   NaN   NaN  51.0   NaN  62.0

174   NaN  72.0   6.0   NaN  65.0
row 34 64
        0     1     2     3     4
415  53.0   NaN   NaN  59.0   NaN
416   NaN   NaN   NaN   NaN  15.0
417   NaN  30.0  43.0   NaN   NaN
418   NaN   6.0  60.0   NaN   NaN
419   NaN   NaN   NaN   NaN   NaN
row 83 64
        0     1    2     3     4
495  38.0   NaN  NaN   NaN   NaN
496  25.0  22.0  NaN   NaN   NaN
497   NaN   NaN  NaN   NaN   NaN
498  75.0   NaN  0.0  65.0   4.0
499  87.0   NaN  NaN   NaN  12.0
row 99 64
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 65
        0     1     2   3     4
145   NaN  93.0  51.0 NaN   NaN
146   NaN   NaN  53.0 NaN   NaN
147   NaN  94.0   NaN NaN  62.0
148  81.0   NaN   NaN NaN  90.0
149   NaN  67.0   NaN NaN   NaN
column 29 65
        0     1     2    3     4
210  62.0   NaN   NaN  0.0  75.0
211   NaN   NaN  60.0  NaN  59.0
212   NaN  43.0   NaN  NaN   NaN
213   NaN   NaN   NaN  NaN   NaN
214   NaN  90.0   NaN  NaN  38.0
row 42 65
        0     1     2     3     4
220  16.0   NaN   NaN  65.0   NaN
221  62.0   NaN   NaN   NaN   NaN
222   NaN   NaN  67.0   2.0  90.0
223   NaN   NaN   NaN   NaN   NaN
224   NaN  53.0   NaN  93.0   NaN
row 44 65
      0     1     2     3     4
360 NaN   8.0  33.0   NaN  16.0
361 NaN   NaN   NaN   NaN  27.0
362 NaN  72.0   NaN  43.0   2.0
363 NaN   NaN   NaN   NaN  81.0
364 NaN   NaN   NaN  90.0   NaN
column 72 65
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 66
       0   1     2     3    4
75   NaN NaN   NaN  19.0  7.0
76   NaN NaN   NaN   NaN  6.0
77  87.0 NaN   2.0   NaN  NaN
78   8.0 NaN  40.0   NaN  NaN
79   NaN NaN   NaN  65.0  NaN
column 15 66
        0     1     2     3   4
175   NaN   NaN   4.0   NaN NaN
176  15.0   NaN   NaN   NaN NaN
177   NaN   NaN  69.0  16.0 NaN
178   NaN  12.0   NaN   NaN NaN
179   NaN  27.0   NaN   NaN NaN
column 35 66
        0   1     2     3    4
285  81.0 NaN  67.0   NaN  NaN
286   NaN NaN   NaN   NaN  4.0
287   NaN NaN   8.0   NaN  NaN
288  90.0 NaN   NaN   NaN  NaN
289  33.0 NaN  43.0  75.0  NaN
column 57 66
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 67
        0     1     2     3   4
280   NaN   8.0   NaN   NaN NaN
281  33.0   NaN   NaN   NaN NaN
282   NaN   NaN  27.0   NaN NaN
283   NaN  40.0   NaN   6.0 NaN
284   NaN   NaN   NaN  72.0 NaN
column 56 67
        0     1    2     3     4
440   NaN   NaN  NaN   NaN   NaN
441   NaN  15.0  NaN   NaN   NaN
442   NaN   NaN  4.0   NaN  16.0
443   NaN   NaN  NaN  12.0   NaN
444  60.0  65.0  NaN   NaN   NaN
row 88 67
      0     1     2     3     4
480 NaN   NaN   NaN   NaN  39.0
481 NaN   NaN  33.0  25.0   8.0
482 NaN   NaN   NaN  59.0  93.0
483 NaN  67.0   NaN   NaN   6.0
484 NaN   NaN   NaN   NaN   NaN
row 96 67
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 68
      0     1     2     3     4
160 NaN  22.0  65.0   NaN  39.0
161 NaN   NaN   NaN   4.0   NaN
162 NaN   NaN  60.0  33.0  40.0
163 NaN   NaN   NaN   2.0   NaN
164 NaN  62.0  67.0  53.0   NaN
column 32 68
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 69
        0   1     2     3     4
180  60.0 NaN   NaN   NaN   NaN
181   NaN NaN   NaN   4.0   NaN
182   NaN NaN   NaN  65.0  40.0
183   NaN NaN   NaN   NaN  43.0
184   NaN NaN  12.0   NaN   NaN
column 36 69
        0     1     2     3     4
345   NaN  60.0   NaN   NaN   NaN
346   NaN   NaN  59.0   NaN   NaN
347  19.0   NaN  53.0  22.0   NaN
348   NaN   NaN   NaN   NaN   NaN
349   NaN  15.0   NaN   NaN  33.0
row 69 69
        0     1     2     3     4
465   NaN  65.0  39.0   6.0   NaN
466   NaN  43.0   8.0   NaN  27.0
467  72.0   NaN   0.0  25.0   NaN
468   NaN   2.0   NaN   NaN   NaN
469   NaN   NaN   NaN   NaN   NaN
row 93 69
       0   1     2     3     4
35   NaN NaN   4.0   NaN   NaN
36  59.0 NaN   NaN   NaN   NaN
37   NaN NaN   NaN  33.0  40.0
38  19.0 NaN   NaN   NaN   NaN
39   NaN NaN  12.0  43.0  75.0
column 7 70
     0   1     2     3   4
45  90 NaN   NaN   8.0 NaN
46  40 NaN   NaN  62.0 NaN
47  60 NaN   NaN   NaN NaN
48  15 NaN   NaN   NaN NaN
49  93 NaN  72.0   NaN NaN
column 9 70
       0     1     2     3     4
110  0.0   NaN   NaN   NaN   NaN
111  NaN   NaN   NaN   NaN  33.0
112  NaN   6.0  75.0  40.0   NaN
113  NaN   NaN   NaN   NaN   NaN
114  NaN  67.0   NaN   NaN   8.0
row 22 70
       0   1     2     3   4
45  90.0 NaN   NaN   8.0 NaN
46  40.0 NaN   NaN  62.0 NaN
47  60.0 NaN   NaN   NaN NaN
48   NaN NaN   NaN   NaN NaN
49  93.0 NaN  72.0   NaN NaN
row 9 71
        0     1     2     3     4
120  22.0  90.0   NaN   NaN  40.0
121   NaN  67.0   NaN   4.0   NaN
122  39.0   NaN  16.0   NaN   NaN
123   NaN   NaN   NaN   NaN   NaN
124  19.0   NaN  43.0  62.0   NaN
row 24 71
        0   1     2     3     4
405   NaN NaN   NaN  90.0   NaN
406   NaN NaN   NaN  33.0   NaN
407   NaN NaN   NaN   NaN  25.0
408  27.0 NaN   NaN   NaN  60.0
409   NaN NaN  72.0   NaN   NaN
column 81 71
        0     1     2     3     4
245  39.0   NaN  67.0   NaN   NaN
246   NaN   NaN   7.0   NaN   NaN
247   NaN  75.0   NaN  62.0   NaN
248   NaN   NaN   NaN   NaN   NaN
249   NaN   0.0   NaN   NaN  33.0
row 49 73
        0     1   2    3     4
330   NaN   NaN NaN  NaN   2.0
331  94.0   NaN NaN  NaN   NaN
332   NaN  39.0 NaN  NaN   NaN
333   NaN  75.0 NaN  8.0  19.0
334   NaN   NaN NaN  NaN  67.0
column 66 73
        0     1     2     3     4
445   NaN  67.0  90.0  27.0   NaN
446   NaN   NaN  40.0   NaN  19.0
447  43.0   NaN   NaN   NaN   NaN
448   NaN   NaN   NaN   NaN   NaN
449   NaN  39.0   NaN  75.0   NaN
row 89 73
       0    1   2     3     4
30  33.0  NaN NaN   NaN   NaN
31  90.0  0.0 NaN   NaN   NaN
32   NaN  NaN NaN   NaN  75.0
33   NaN  NaN NaN  67.0  22.0
34   NaN  NaN NaN   NaN  94.0
column 6 75
        0    1   2     3     4
125   NaN  7.0 NaN   NaN  33.0
126  93.0  NaN NaN   NaN   NaN
127   NaN  NaN NaN   NaN   NaN
128   NaN  NaN NaN  19.0   NaN
129   2.0  NaN NaN  53.0   NaN
row 25 76
        0     1     2    3     4
425  38.0   NaN   NaN  NaN   NaN
426  75.0   NaN   NaN  4.0   NaN
427   NaN  72.0  94.0  NaN  19.0
428   NaN  90.0   NaN  NaN   NaN
429   NaN   NaN   NaN  NaN   NaN
row 85 76
      0     1    2     3     4
375 NaN  59.0  NaN  19.0  53.0
376 NaN   NaN  0.0   NaN   NaN
377 NaN   NaN  NaN   NaN  25.0
378 NaN   NaN  NaN   NaN   NaN
379 NaN   NaN  NaN   NaN  62.0
row 75 77
        0     1     2     3     4
195   NaN   NaN   NaN   8.0   NaN
196   NaN   NaN  25.0  12.0  22.0
197  27.0  75.0   NaN  93.0   NaN
198   NaN   NaN   NaN   NaN   NaN
199   NaN  40.0   NaN  60.0   NaN
row 39 78
        0     1     2     3     4
250  19.0   NaN  87.0  72.0  90.0
251   NaN   NaN   NaN   8.0   NaN
252   NaN   NaN   4.0   NaN   NaN
253   NaN  62.0  25.0   NaN   NaN
254   NaN   NaN   NaN   NaN   NaN
row 50 78
        0   1     2     3     4
390  12.0 NaN   NaN   NaN   NaN
391  75.0 NaN   NaN  25.0   NaN
392   NaN NaN  62.0   NaN  33.0
393  27.0 NaN   NaN   NaN   NaN
394   NaN NaN  87.0   NaN   0.0
column 78 78
        0   1     2     3    4
135   NaN NaN  27.0  60.0  NaN
136   NaN NaN  94.0   NaN  NaN
137   NaN NaN  75.0   NaN  NaN
138  87.0 NaN   NaN   NaN  NaN
139   NaN NaN   NaN   NaN  2.0
column 27 79
       0   1     2     3    4
95  27.0 NaN   NaN   NaN  NaN
96   NaN NaN   NaN   NaN  4.0
97   NaN NaN  62.0   NaN  NaN
98   NaN NaN   NaN  53.0  NaN
99   NaN NaN   NaN  12.0  NaN
column 19 80
        0    1     2     3    4
485   NaN  NaN   NaN  62.0  NaN
486   NaN  NaN   NaN   NaN  8.0
487   NaN  NaN   NaN   NaN  NaN
488  22.0  NaN   NaN   NaN  NaN
489  90.0  2.0  94.0   NaN  NaN
row 97 80
        0     1     2     3     4
260  12.0  87.0   NaN   NaN   NaN
261   NaN   NaN   NaN   NaN  27.0
262   NaN   NaN   NaN   NaN   NaN
263   NaN   NaN   0.0   NaN   NaN
264   NaN   NaN  25.0  53.0   NaN
row 52 81

        0     1   2     3     4
420   NaN   NaN NaN   NaN  19.0
421   NaN  87.0 NaN   NaN   NaN
422   NaN  62.0 NaN  38.0   NaN
423  53.0   NaN NaN  12.0   NaN
424   NaN   NaN NaN   NaN   NaN
row 84 83
       0     1     2   3     4
115  NaN   NaN  94.0 NaN   NaN
116  8.0   NaN   NaN NaN   NaN
117  NaN   NaN   NaN NaN   NaN
118  NaN   NaN  12.0 NaN   NaN
119  NaN  93.0   NaN NaN  27.0
row 23 85
        0   1     2     3     4
325   NaN NaN   NaN  12.0   NaN
326   NaN NaN   NaN   NaN  27.0
327   NaN NaN  38.0   NaN   NaN
328   NaN NaN   NaN   8.0   NaN
329  87.0 NaN   NaN   NaN   NaN
column 65 87

In [148]:
sum(lastwinner.sum()) * numbers[lastnumber]

16168.0

In [147]:
lastwinner

        0   1     2     3     4
325   NaN NaN   NaN  12.0   NaN
326   NaN NaN   NaN   NaN  27.0
327   NaN NaN  38.0   NaN   NaN
328   NaN NaN   NaN   8.0   NaN
329  87.0 NaN   NaN   NaN   NaN